# Generated by Django 6.1.1 on 2026-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('accommodation_type', models.CharField(choices=[('red_panda', 'Red Panda Lodge (£150/night)'), ('panda_suite', 'Panda Sanctuary Suite (£220/night)'), ('safari_cabin', 'Wildlife Safari Cabin (£180/night)')], max_length=50)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveIntegerField(default=2)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
